name: continuous-integration

on:
  push:
    branches:
      - main
      - releases/*
  pull_request: null

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  CONDA_ENV: .github/environment.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12"]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - name: Checkout SOOPERCOOL repository
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: |
              3.9
              3.10
              3.11
              3.12

      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11
  
      - run: ${{ env.FC }} --version
        env:
          FC: ${{ steps.setup-fortran.outputs.fc }}

      - name: Install dependencies
        run: |
          sudo -H apt-get install libgsl-dev libfftw3-dev libcfitsio-dev

      - name: Install soopercool & dependencies
        run: |
          python -m pip install -U pip
          pip install -U wheel
          pip install -U setuptools
          pip install -U numpy
          pip install -U scipy
          pip install -U healpy
          pip install -U sacc
          pip install -U camb
          pip install -U pymaster
          pip install -U flake8
          pip install -U pytest
          pip install -U pytest-cov
          pip install -U coveralls
          python setup.py install

      - name: Lint
        uses: py-actions/flake8@v2
        with:
          args: "--config .flake8"
          max-line-length: "100"
          ignore: "E203,E226,W503"

      - name: Tests
        run: pytest -vv --cov=soopercool 
        
